ElmålingsSystem.MVC/Controllers/InstallationController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNamespace;

namespace ElmålingsSystem.MVC.Controllers
{
    [Route("installation")]
    [Authorize]
    public class InstallationController : Controller
    {
        private readonly IClient _clientService;
        public InstallationController(IClient clientService)
        {
            _clientService = clientService;
        }

        [Route("alle_installationer")]
        public async Task<IActionResult> Index(int cprNr)
        {
            var installation = await _clientService.GetAllInstallationerAsync(cprNr).ConfigureAwait(false);
            return View(installation);
        }

        [Route("installation")]
        public async Task <IActionResult> InstallationIndex(int installationsId)
        {
            var installation = await _clientService.GetInstallationAsync(installationsId).ConfigureAwait(false);
            return View(installation);
        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("ny_installation")]
        public IActionResult PostInstallation(int cprnr)
        {
            TempData["cprnr"] = cprnr;
            return View();
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ny_installation")]
        public async Task<IActionResult> PostInstallation(InstallationLinked installation)
        {
            var s = TempData["cprnr"];
            await _clientService.PostInstallationAsync(Convert.ToInt32(s), installation).ConfigureAwait(false);
            return RedirectToAction("Index", "Kunde");
        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("redigere_installation")]
        public async Task<IActionResult> PutInstallation(int InstallationsId)
        {
            TempData["installationsid"] = InstallationsId;
            var installation = await _clientService.GetInstallationAsync(InstallationsId).ConfigureAwait(false);
            return View(installation);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("redigere_installation")]
        public async Task<IActionResult> PutInstallation(InstallationLinked installation)
        {
            var s = TempData["installationsid"];
            await _clientService.PutInstallationAsync(Convert.ToInt32(s), installation).ConfigureAwait(false);
            return RedirectToAction("Index", "Kunde");
        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("slet_installation")]
        public async Task<IActionResult> DeleteInstallation(int installationsId, int dummy)
        {
            TempData["Sletinstallationsid"] = installationsId;
            var installation = await _clientService.GetInstallationAsync(installationsId).ConfigureAwait(false);
            return View(installation);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [Route("slet_installation")]
        public async Task<IActionResult> DeleteInstallation(int cprnr)
        {
            var slet = TempData["Sletinstallationsid"];
            await _clientService.DeleteInstallationAsync(Convert.ToInt32(slet)).ConfigureAwait(false);
            return RedirectToAction("Index", "Kunde");
        }
    }
}

ElmålingsSystem.MVC/Controllers/LejerKundeController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNamespace;

namespace ElmålingsSystem.MVC.Controllers
{
    [Route("lejer")]
    [Authorize("LejerMedarbejder")]
    public class LejerKundeController : Controller
    {
        private readonly IClient _clientService;
        public LejerKundeController(IClient clientService)
        {
            _clientService = clientService;
        }

        [Route("lejer")]
        public async Task<IActionResult> LejerkundeIndex(int cprnr)
        {
            var lejerkunde = await _clientService.GetLejerKundeByIdAsync(cprnr).ConfigureAwait(false);
            return View(lejerkunde);
        }

        [Route("lejerer")]
        public async Task<IActionResult> Index()
        {
            var lejerkunder = await _clientService.GetAllLejerKunderAsync().ConfigureAwait(false);
            return View(lejerkunder);

        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("ny_lejer")]
        public IActionResult PostLejerKunde(int installationsid)
        {
            TempData["PostInstallation"] = installationsid;
            return View();
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ny_lejer")]
        public async Task<IActionResult> PostLejerKunde(LejerKundeLinked lejerkunde)
        {
            var installationsId = TempData["PostInstallation"];
            await _clientService.PostLejerKundeAsync(Convert.ToInt32(installationsId), lejerkunde).ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        [Authorize("LejerMedarbejder")]
        [HttpGet]
        [Route("redigere_lejer")]
        public async Task<IActionResult> PutLejerKunde(int cprnr)
        {
            var model = await _clientService.GetLejerKundeByIdAsync(cprnr).ConfigureAwait(false);
            TempData["LejerId"] = model.KundeId;
            return View(model);
        }

        [Authorize("LejerMedarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("redigere_lejer")]
        public async Task<IActionResult> PutLejerKunde(LejerKundeLinked lejerKunde)
        {
            var putLejer = TempData["LejerId"];
            await _clientService.PutLejerKundeByIdAsync(Convert.ToInt32(putLejer), lejerKunde).ConfigureAwait(false);
            return RedirectToAction("Index", "Home");

        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("slet_lejer")]
        public async Task<IActionResult> DeleteLejerKunde(int cprnr, int dummy)
        {
            TempData["SletLejer"] = cprnr;
            var model = await _clientService.GetLejerKundeByIdAsync(cprnr).ConfigureAwait(false);
            return View(model);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [Route("slet_lejer")]
        public async Task<IActionResult> DeleteLejerKunde(int cprnr)
        {
            var slet = TempData["SletLejer"];
            await _clientService.DeleteLejerKundeByIdAsync(Convert.ToInt32(slet)).ConfigureAwait(false);
            return RedirectToAction("Index");
        }
    }
}

ElmålingsSystem.MVC/Controllers/MålerController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNamespace;

namespace ElmålingsSystem.MVC.Controllers
{
    [Route("maaler")]
    [Authorize]
    public class MålerController : Controller
    {
        private readonly IClient _clientService;
        public MålerController(IClient clientService)
        {
            _clientService = clientService;
        }

        [Route("maaler")]
        public async Task<IActionResult> MålerIndex(int installationsId)
        {
            TempData["installationsID"] = installationsId;
            var måler = await _clientService.GetMålerByInstallationsIdAsync(installationsId).ConfigureAwait(false);
            return View(måler);
        }
        [HttpGet]
        [Route("ny_maaler")]
        public IActionResult PostMåler(int installationsid)
        {
            TempData["PostInstallation"] = installationsid;
            return View();
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ny_maaler")]
        public async Task<IActionResult> PostMåler(MålerLinked måler)
        {
            var installationsId = TempData["PostInstallation"];
            await _clientService.PostMålerAsync(Convert.ToInt32(installationsId), måler).ConfigureAwait(false);
            return RedirectToAction("Index", "Home");
        }


        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("slet_maaler")]
        public async Task<IActionResult> DeleteMåler(int dummy)
        {
            var installationsid = TempData["installationsID"];
            var model = await _clientService.GetMålerByInstallationsIdAsync(Convert.ToInt32(installationsid)).ConfigureAwait(false);
            TempData["SletMåler"] = model.MålerId;
            return View(model);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [Route("slet_maaler")]
        public async Task<IActionResult> DeleteMåler()
        {
            var slet = TempData["SletMåler"];
            await _clientService.DeleteMålerByIdAsync(Convert.ToInt32(slet)).ConfigureAwait(false);
            return RedirectToAction("Index", "Home");
        }
    }
}

ElmålingsSystem.MVC/Views/Installation/DeleteInstallation.cshtml
@model MyNamespace.InstallationLinked

@{
    ViewData["Title"] = "DeleteInstallation";
}

<h1>Slet Installation</h1>

<h3>Er du sikker på du vil slette installationen?</h3>
<div>
    <h4>Installation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ForventetÅrsforbrug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ForventetÅrsforbrug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AflæsningsFrekvens)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AflæsningsFrekvens)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aflæsningsform)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aflæsningsform)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Afbrydelsesart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Afbrydelsesart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tilslutningstype)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tilslutningstype)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffektgrænseAmpere)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffektgrænseAmpere)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffektgrænseKW)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffektgrænseKW)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VejNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VejNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HusNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HusNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dør)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dør)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ByNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ByNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LandeKode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LandeKode)
        </dd>        
    </dl>
    
    <form asp-action="DeleteInstallation">
        <input type="hidden" asp-for="InstallationsId" />
        <input type="submit" value="Slet" class="btn btn-danger" />       
    </form>
</div>

ElmålingsSystem.MVC/Views/Installation/Index.cshtml
@model IEnumerable<MyNamespace.InstallationLinked>

@{
    ViewData["Title"] = "Index";
}

<h1>Alle Installationer</h1>

<table class="table">
    <thead>
        <tr>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.InstallationsId)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.ForventetÅrsforbrug)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.AflæsningsFrekvens)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.Aflæsningsform)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.Afbrydelsesart)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.Tilslutningstype)
            </th>                  
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InstallationsId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ForventetÅrsforbrug)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AflæsningsFrekvens)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aflæsningsform)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Afbrydelsesart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tilslutningstype)
            </td>                   
            <td>
                
            <a asp-action="InstallationIndex" asp-route-InstallationsId="@item.InstallationsId">Detaljer</a>
                  
        @if (User.IsInRole("Medarbejder"))
        {
                        
                <a asp-action="PutInstallation" asp-route-InstallationsId="@item.InstallationsId">Ændre</a>
                        

                <a asp-action="DeleteInstallation" asp-route-InstallationsId="@item.InstallationsId">Slet</a>
                        
        }
                
            </td>
        </tr>
        }
    </tbody>
</table>

ElmålingsSystem.MVC/Views/Installation/InstallationIndex.cshtml
@model MyNamespace.InstallationLinked

@{
    ViewData["Title"] = "InstallationIndex";
}

<h1>Installation</h1>

<div>
    <h4>Installation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ForventetÅrsforbrug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ForventetÅrsforbrug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AflæsningsFrekvens)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AflæsningsFrekvens)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aflæsningsform)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aflæsningsform)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Afbrydelsesart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Afbrydelsesart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tilslutningstype)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tilslutningstype)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffektgrænseAmpere)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffektgrænseAmpere)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffektgrænseKW)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffektgrænseKW)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VejNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VejNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HusNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HusNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dør)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dør)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ByNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ByNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LandeKode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LandeKode)
        </dd>        
    </dl>
</div>
<div>
    <ul>
        <li>
            <a asp-controller="Måler" asp-action="MålerIndex" asp-route-InstallationsId="@Model.InstallationsId">Se måler</a>
        </li>
     @if (User.IsInRole("Medarbejder"))
      {
         <li>
             <a asp-controller="Måler" asp-action="PostMåler" asp-route-InstallationsId="@Model.InstallationsId">Opret ny måler</a>
         </li>
         <li>
             <a asp-controller="LejerKunde" asp-action="PostLejerKunde" asp-route-InstallationsId="@Model.InstallationsId">Opret ny Lejer</a>
         </li>
         <li>
             <a asp-action="PutInstallation" asp-route-InstallationsId="@Model.InstallationsId">Ændre</a>
         </li>
      }
    
    </ul>
</div>

ElmålingsSystem.MVC/Views/Installation/PostInstallation.cshtml
@model MyNamespace.InstallationLinked


@{
    ViewData["Title"] = "PostInstallation";
}

<h1>Oprettelse af ny installation</h1>

<h4>Installation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PostInstallation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ForventetÅrsforbrug" class="control-label"></label>
                <input asp-for="ForventetÅrsforbrug" class="form-control" />
                <span asp-validation-for="ForventetÅrsforbrug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AflæsningsFrekvens" class="control-label"></label>
                <input asp-for="AflæsningsFrekvens" class="form-control" />
                <span asp-validation-for="AflæsningsFrekvens" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aflæsningsform" class="control-label"></label>
                <input asp-for="Aflæsningsform" class="form-control" />
                <span asp-validation-for="Aflæsningsform" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Afbrydelsesart" class="control-label"></label>
                <input asp-for="Afbrydelsesart" class="form-control" />
                <span asp-validation-for="Afbrydelsesart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tilslutningstype" class="control-label"></label>
                <input asp-for="Tilslutningstype" class="form-control" />
                <span asp-validation-for="Tilslutningstype" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffektgrænseAmpere" class="control-label"></label>
                <input asp-for="EffektgrænseAmpere" class="form-control" />
                <span asp-validation-for="EffektgrænseAmpere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffektgrænseKW" class="control-label"></label>
                <input asp-for="EffektgrænseKW" class="form-control" />
                <span asp-validation-for="EffektgrænseKW" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VejNavn" class="control-label"></label>
                <input asp-for="VejNavn" class="form-control" />
                <span asp-validation-for="VejNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HusNummer" class="control-label"></label>
                <input asp-for="HusNummer" class="form-control" />
                <span asp-validation-for="HusNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Etage" class="control-label"></label>
                <input asp-for="Etage" class="form-control" />
                <span asp-validation-for="Etage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dør" class="control-label"></label>
                <input asp-for="Dør" class="form-control" />
                <span asp-validation-for="Dør" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostNummer" class="control-label"></label>
                <input asp-for="PostNummer" class="form-control" />
                <span asp-validation-for="PostNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ByNavn" class="control-label"></label>
                <input asp-for="ByNavn" class="form-control" />
                <span asp-validation-for="ByNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LandeKode" class="control-label"></label>
                <input asp-for="LandeKode" class="form-control" />
                <span asp-validation-for="LandeKode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Opret" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ElmålingsSystem.MVC/Views/Installation/PutInstallation.cshtml
@model MyNamespace.InstallationLinked

@{
    ViewData["Title"] = "PutInstallation";
}

<h1>Ændre oplysninger om installationen</h1>

<h4>Installation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PutInstallation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InstallationsId" />
            <div class="form-group">
                <label asp-for="ForventetÅrsforbrug" class="control-label"></label>
                <input asp-for="ForventetÅrsforbrug" class="form-control" />
                <span asp-validation-for="ForventetÅrsforbrug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AflæsningsFrekvens" class="control-label"></label>
                <input asp-for="AflæsningsFrekvens" class="form-control" />
                <span asp-validation-for="AflæsningsFrekvens" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aflæsningsform" class="control-label"></label>
                <input asp-for="Aflæsningsform" class="form-control" />
                <span asp-validation-for="Aflæsningsform" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Afbrydelsesart" class="control-label"></label>
                <input asp-for="Afbrydelsesart" class="form-control" />
                <span asp-validation-for="Afbrydelsesart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tilslutningstype" class="control-label"></label>
                <input asp-for="Tilslutningstype" class="form-control" />
                <span asp-validation-for="Tilslutningstype" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffektgrænseAmpere" class="control-label"></label>
                <input asp-for="EffektgrænseAmpere" class="form-control" />
                <span asp-validation-for="EffektgrænseAmpere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffektgrænseKW" class="control-label"></label>
                <input asp-for="EffektgrænseKW" class="form-control" />
                <span asp-validation-for="EffektgrænseKW" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VejNavn" class="control-label"></label>
                <input asp-for="VejNavn" class="form-control" />
                <span asp-validation-for="VejNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HusNummer" class="control-label"></label>
                <input asp-for="HusNummer" class="form-control" />
                <span asp-validation-for="HusNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Etage" class="control-label"></label>
                <input asp-for="Etage" class="form-control" />
                <span asp-validation-for="Etage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dør" class="control-label"></label>
                <input asp-for="Dør" class="form-control" />
                <span asp-validation-for="Dør" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostNummer" class="control-label"></label>
                <input asp-for="PostNummer" class="form-control" />
                <span asp-validation-for="PostNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ByNavn" class="control-label"></label>
                <input asp-for="ByNavn" class="form-control" />
                <span asp-validation-for="ByNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LandeKode" class="control-label"></label>
                <input asp-for="LandeKode" class="form-control" />
                <span asp-validation-for="LandeKode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Opdater" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}