ElmålingsSystem.MVC/Controllers/KundeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNamespace;

namespace ElmålingsSystem.MVC.Controllers
{
    [Route("ejer")]
    [Authorize("EjerMedarbejder")] 
    public class KundeController : Controller
    {
        private readonly IClient _clientService;
        public KundeController(IClient clientService)
        {
            _clientService = clientService;
        }

        [Route("ejer")]
        public async Task <IActionResult> EjerkundeIndex(int cprnr)
        {
            
            var ejerkunde = await _clientService.GetEjerKundeAsync(cprnr).ConfigureAwait(false);
            return View(ejerkunde);
        }
        [Route("ejerer")]
        public async Task<IActionResult> Index()
        {
            var ejerkunder = await _clientService.GetAllEjerKunderAsync().ConfigureAwait(false);
            return View(ejerkunder);
            
        }

        [Authorize("Medarbejder")]
        [HttpGet]        
        [Route("ny_ejer")]
        public IActionResult PostEjerKunde()
        {
            return View();
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ny_ejer")]
        public async Task <IActionResult> PostEjerKunde(EjerKundeLinked ejerkunde)
        {
            await _clientService.PostEjerKundeAsync(ejerkunde).ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        
        [HttpGet]
        [Route("redigere_ejer")]
        public async Task <IActionResult> PutEjerKunde(int cprnr)
        {
            
            var model = await _clientService.GetEjerKundeAsync(cprnr).ConfigureAwait(false);
            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("redigere_ejer")]
        public async Task <IActionResult> PutEjerKunde(EjerKundeLinked ejerKunde)
        {
            await _clientService.PutEjerKundeAsync(ejerKunde.KundeId, ejerKunde).ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("slet_ejer")]
        public async Task<IActionResult> DeleteEjerKunde(int cprnr,int dummy)
        {
            var model = await _clientService.GetEjerKundeAsync(cprnr).ConfigureAwait(false);
            return View(model);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [Route("slet_ejer")]
        public async Task<IActionResult> DeleteEjerKunde(int cprnr)
        {
            await _clientService.DeleteEjerKundeAsync(cprnr).ConfigureAwait(false);
            return RedirectToAction("Index");
        }
    }
}

ElmålingsSystem.MVC/Controllers/MålerController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNamespace;

namespace ElmålingsSystem.MVC.Controllers
{
    [Route("maaler")]
    [Authorize]
    public class MålerController : Controller
    {
        private readonly IClient _clientService;
        public MålerController(IClient clientService)
        {
            _clientService = clientService;
        }

        [Route("maaler")]
        public async Task<IActionResult> MålerIndex(int installationsId)
        {
            TempData["installationsID"] = installationsId;
            var måler = await _clientService.GetMålerByInstallationsIdAsync(installationsId).ConfigureAwait(false);
            return View(måler);
        }
        [HttpGet]
        [Route("ny_maaler")]
        public IActionResult PostMåler(int installationsid)
        {
            TempData["PostInstallation"] = installationsid;
            return View();
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ny_maaler")]
        public async Task<IActionResult> PostMåler(MålerLinked måler)
        {
            var installationsId = TempData["PostInstallation"];
            await _clientService.PostMålerAsync(Convert.ToInt32(installationsId), måler).ConfigureAwait(false);
            return RedirectToAction("Index", "Home");
        }


        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("slet_maaler")]
        public async Task<IActionResult> DeleteMåler(int dummy)
        {
            var installationsid = TempData["installationsID"];
            var model = await _clientService.GetMålerByInstallationsIdAsync(Convert.ToInt32(installationsid)).ConfigureAwait(false);
            TempData["SletMåler"] = model.MålerId;
            return View(model);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [Route("slet_maaler")]
        public async Task<IActionResult> DeleteMåler()
        {
            var slet = TempData["SletMåler"];
            await _clientService.DeleteMålerByIdAsync(Convert.ToInt32(slet)).ConfigureAwait(false);
            return RedirectToAction("Index", "Home");
        }
    }
}

ElmålingsSystem.MVC/Controllers/StatistikController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNamespace;

namespace ElmålingsSystem.MVC.Controllers
{
    [Route("statistik")]
    [Authorize]
    public class StatistikController : Controller
    {
        private readonly IClient _clientService;
        public StatistikController(IClient clientService)
        {
            _clientService = clientService;
        }

        [HttpGet]
        [Route("statistik_mellem_to_datoer")]
        public async Task<IActionResult> StatistikIndex(int målerid, DateTime? start, DateTime? slut)
        {
           
            TempData["målerId"] = målerid;
            if (!start.HasValue)
            {
                start = DateTime.Now.AddMonths(-1);
                slut = DateTime.Now;

            }
            var statistik = await _clientService.GetAllMåleVærdierFromMålerIdAndDateAsync(målerid, start, slut).ConfigureAwait(false);
            return View(statistik);
        }

        [HttpPost]
        [Route("statistik_mellem_to_datoer")]
        public async Task<IActionResult> StatistikIndex(DateTime start, DateTime slut)
        {
            int måler = Convert.ToInt32(TempData["målerId"]);
            await _clientService.GetAllMåleVærdierFromMålerIdAndDateAsync(måler, start, slut);
            return await StatistikIndex(måler, start, slut);
            
        }
    }
}

ElmålingsSystem.MVC/Views/Måler/DeleteMåler.cshtml
@model MyNamespace.MålerLinked

@{
    ViewData["Title"] = "DeleteMåler";
}

<h1>Slet måler</h1>

<h3>Er du sikker på du vil slette denne måler?</h3>
<div>
    <h4>Måler</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MåleromregningsFaktor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MåleromregningsFaktor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MålerCifre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MålerCifre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Målertype)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Målertype)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Målingsenhed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Målingsenhed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MålerBeskrivelse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MålerBeskrivelse)
        </dd>        
    </dl>
    
    <form asp-action="DeleteMåler">
        <input type="hidden" asp-for="MålerId" />
        <input type="submit" value="Slet" class="btn btn-danger" /> |
        <a asp-controller="Kunde" asp-action="Index">Tilbage til alle ejerkunder</a>
    </form>
</div>

ElmålingsSystem.MVC/Views/Måler/MålerIndex.cshtml
@model MyNamespace.MålerLinked

@{
    ViewData["Title"] = "MålerIndex";
}

<h1>Måler</h1>

<div>
    <h4>Måler</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MåleromregningsFaktor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MåleromregningsFaktor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MålerCifre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MålerCifre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Målertype)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Målertype)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Målingsenhed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Målingsenhed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MålerBeskrivelse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MålerBeskrivelse)
        </dd>        
    </dl>
</div>
<div>
    <ul>
        <li>
            <a asp-controller="Statistik" asp-action="StatistikIndex" asp-route-MålerId="@Model.MålerId">Se Statistik</a>
        </li>
        @if (User.IsInRole("Medarbejder"))
        {
            <li>
                <a asp-action="DeleteMåler" asp-route-MålerId="@Model.MålerId">Slet</a>
            </li>
        }
    </ul>
    
</div>

ElmålingsSystem.MVC/Views/Måler/PostMåler.cshtml
@model MyNamespace.MålerLinked

@{
    ViewData["Title"] = "PostMåler";
}

<h1>Opret ny måler</h1>

<h4>Måler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PostMåler">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MåleromregningsFaktor" class="control-label"></label>
                <input asp-for="MåleromregningsFaktor" class="form-control" />
                <span asp-validation-for="MåleromregningsFaktor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MålerCifre" class="control-label"></label>
                <input asp-for="MålerCifre" class="form-control" />
                <span asp-validation-for="MålerCifre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Målertype" class="control-label"></label>
                <input asp-for="Målertype" class="form-control" />
                <span asp-validation-for="Målertype" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Målingsenhed" class="control-label"></label>
                <input asp-for="Målingsenhed" class="form-control" />
                <span asp-validation-for="Målingsenhed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MålerBeskrivelse" class="control-label"></label>
                <input asp-for="MålerBeskrivelse" class="form-control" />
                <span asp-validation-for="MålerBeskrivelse" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Opret" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Kunde" asp-action="Index">Tilbage til alle ejerkunder</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}