ElmålingsSystem.MVC/Controllers/InstallationController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNamespace;

namespace ElmålingsSystem.MVC.Controllers
{
    [Route("installation")]
    [Authorize]
    public class InstallationController : Controller
    {
        private readonly IClient _clientService;
        public InstallationController(IClient clientService)
        {
            _clientService = clientService;
        }

        [Route("alle_installationer")]
        public async Task<IActionResult> Index(int cprNr)
        {
            var installation = await _clientService.GetAllInstallationerAsync(cprNr).ConfigureAwait(false);
            return View(installation);
        }

        [Route("installation")]
        public async Task <IActionResult> InstallationIndex(int installationsId)
        {
            var installation = await _clientService.GetInstallationAsync(installationsId).ConfigureAwait(false);
            return View(installation);
        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("ny_installation")]
        public IActionResult PostInstallation(int cprnr)
        {
            TempData["cprnr"] = cprnr;
            return View();
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ny_installation")]
        public async Task<IActionResult> PostInstallation(InstallationLinked installation)
        {
            var s = TempData["cprnr"];
            await _clientService.PostInstallationAsync(Convert.ToInt32(s), installation).ConfigureAwait(false);
            return RedirectToAction("Index", "Kunde");
        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("redigere_installation")]
        public async Task<IActionResult> PutInstallation(int InstallationsId)
        {
            TempData["installationsid"] = InstallationsId;
            var installation = await _clientService.GetInstallationAsync(InstallationsId).ConfigureAwait(false);
            return View(installation);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("redigere_installation")]
        public async Task<IActionResult> PutInstallation(InstallationLinked installation)
        {
            var s = TempData["installationsid"];
            await _clientService.PutInstallationAsync(Convert.ToInt32(s), installation).ConfigureAwait(false);
            return RedirectToAction("Index", "Kunde");
        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("slet_installation")]
        public async Task<IActionResult> DeleteInstallation(int installationsId, int dummy)
        {
            TempData["Sletinstallationsid"] = installationsId;
            var installation = await _clientService.GetInstallationAsync(installationsId).ConfigureAwait(false);
            return View(installation);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [Route("slet_installation")]
        public async Task<IActionResult> DeleteInstallation(int cprnr)
        {
            var slet = TempData["Sletinstallationsid"];
            await _clientService.DeleteInstallationAsync(Convert.ToInt32(slet)).ConfigureAwait(false);
            return RedirectToAction("Index", "Kunde");
        }
    }
}

ElmålingsSystem.MVC/Controllers/LejerKundeController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNamespace;

namespace ElmålingsSystem.MVC.Controllers
{
    [Route("lejer")]
    [Authorize("LejerMedarbejder")]
    public class LejerKundeController : Controller
    {
        private readonly IClient _clientService;
        public LejerKundeController(IClient clientService)
        {
            _clientService = clientService;
        }

        [Route("lejer")]
        public async Task<IActionResult> LejerkundeIndex(int cprnr)
        {
            var lejerkunde = await _clientService.GetLejerKundeByIdAsync(cprnr).ConfigureAwait(false);
            return View(lejerkunde);
        }

        [Route("lejerer")]
        public async Task<IActionResult> Index()
        {
            var lejerkunder = await _clientService.GetAllLejerKunderAsync().ConfigureAwait(false);
            return View(lejerkunder);

        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("ny_lejer")]
        public IActionResult PostLejerKunde(int installationsid)
        {
            TempData["PostInstallation"] = installationsid;
            return View();
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("ny_lejer")]
        public async Task<IActionResult> PostLejerKunde(LejerKundeLinked lejerkunde)
        {
            var installationsId = TempData["PostInstallation"];
            await _clientService.PostLejerKundeAsync(Convert.ToInt32(installationsId), lejerkunde).ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        [Authorize("LejerMedarbejder")]
        [HttpGet]
        [Route("redigere_lejer")]
        public async Task<IActionResult> PutLejerKunde(int cprnr)
        {
            var model = await _clientService.GetLejerKundeByIdAsync(cprnr).ConfigureAwait(false);
            TempData["LejerId"] = model.KundeId;
            return View(model);
        }

        [Authorize("LejerMedarbejder")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("redigere_lejer")]
        public async Task<IActionResult> PutLejerKunde(LejerKundeLinked lejerKunde)
        {
            var putLejer = TempData["LejerId"];
            await _clientService.PutLejerKundeByIdAsync(Convert.ToInt32(putLejer), lejerKunde).ConfigureAwait(false);
            return RedirectToAction("Index", "Home");

        }

        [Authorize("Medarbejder")]
        [HttpGet]
        [Route("slet_lejer")]
        public async Task<IActionResult> DeleteLejerKunde(int cprnr, int dummy)
        {
            TempData["SletLejer"] = cprnr;
            var model = await _clientService.GetLejerKundeByIdAsync(cprnr).ConfigureAwait(false);
            return View(model);
        }

        [Authorize("Medarbejder")]
        [HttpPost]
        [Route("slet_lejer")]
        public async Task<IActionResult> DeleteLejerKunde(int cprnr)
        {
            var slet = TempData["SletLejer"];
            await _clientService.DeleteLejerKundeByIdAsync(Convert.ToInt32(slet)).ConfigureAwait(false);
            return RedirectToAction("Index");
        }
    }
}

ElmålingsSystem.MVC/Views/LejerKunde/DeleteLejerKunde.cshtml
@model MyNamespace.LejerKundeLinked

@{
    ViewData["Title"] = "DeleteLejerKunde";
}

<h1>Slet kunde</h1>

<h3>Er du sikker på du vil slette denne kunde?</h3>
<div>
    <h4>LejerKunde</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CprNr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CprNr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ForNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ForNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EfterNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EfterNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VejNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VejNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HusNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HusNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dør)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dør)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ByNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ByNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KommuneNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KommuneNavn)
        </dd>        
    </dl>
    
    <form asp-action="DeleteLejerKunde">
        <input type="hidden" asp-for="KundeId" />
        <input type="submit" value="Slet" class="btn btn-danger" /> |
        <a asp-action="Index">Tilbage til alle lejerkunder</a>
    </form>
</div>

ElmålingsSystem.MVC/Views/LejerKunde/Index.cshtml
@model IEnumerable<MyNamespace.LejerKundeLinked>

@{
    ViewData["Title"] = "Index";
}

<h1>Alle lejerkunder</h1>
<table class="table">
    <thead>
        <tr>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.CprNr)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.ForNavn)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.EfterNavn)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.VejNavn)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.HusNummer)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.Etage)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.Dør)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.PostNummer)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.ByNavn)
            </th>
            <th class="col-sm-2">
                @Html.DisplayNameFor(model => model.KommuneNavn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CprNr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ForNavn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EfterNavn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VejNavn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HusNummer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Etage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dør)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostNummer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ByNavn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KommuneNavn)
                </td>
                <td>
                    <a asp-action="PutLejerKunde" asp-route-cprnr="@item.CprNr">Ændre</a> 
                    <a asp-action="LejerkundeIndex" asp-route-CprNr="@item.CprNr">Detaljer</a> 
                    <a asp-action="DeleteLejerKunde" asp-route-cprnr="@item.CprNr">Slet</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ElmålingsSystem.MVC/Views/LejerKunde/LejerkundeIndex.cshtml
@model MyNamespace.LejerKundeLinked

@{
    ViewData["Title"] = "LejerkundeIndex";
}

<h1>Lejerkunde</h1>

<div>
    <h4>LejerKunde</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CprNr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CprNr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ForNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ForNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EfterNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EfterNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VejNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VejNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HusNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HusNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dør)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dør)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostNummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostNummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ByNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ByNavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KommuneNavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KommuneNavn)
        </dd>       
    </dl>
</div>
<div>
    <ul>
        <li>
            <a asp-action="PutLejerKunde" asp-route-cprnr="@Model.CprNr">Ændre</a>
        </li>
        <li>
            <a asp-controller="Installation" asp-action="Index" asp-route-cprnr="@Model.CprNr">Se installation</a>
        </li>
        @if (User.IsInRole("Medarbejder"))
        {
            <li>
                <a asp-action="Index">Tilbage til alle lejerkunder</a>
            </li>
        }
    </ul>
</div>

ElmålingsSystem.MVC/Views/LejerKunde/PostLejerKunde.cshtml
@model MyNamespace.LejerKundeLinked

@{
    ViewData["Title"] = "PostLejerKunde";
}

<h1>Opret ny lejerkunde</h1>

<h4>LejerKunde</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PostLejerKunde">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CprNr" class="control-label"></label>
                <input asp-for="CprNr" class="form-control" />
                <span asp-validation-for="CprNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ForNavn" class="control-label"></label>
                <input asp-for="ForNavn" class="form-control" />
                <span asp-validation-for="ForNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EfterNavn" class="control-label"></label>
                <input asp-for="EfterNavn" class="form-control" />
                <span asp-validation-for="EfterNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VejNavn" class="control-label"></label>
                <input asp-for="VejNavn" class="form-control" />
                <span asp-validation-for="VejNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HusNummer" class="control-label"></label>
                <input asp-for="HusNummer" class="form-control" />
                <span asp-validation-for="HusNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Etage" class="control-label"></label>
                <input asp-for="Etage" class="form-control" />
                <span asp-validation-for="Etage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dør" class="control-label"></label>
                <input asp-for="Dør" class="form-control" />
                <span asp-validation-for="Dør" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostNummer" class="control-label"></label>
                <input asp-for="PostNummer" class="form-control" />
                <span asp-validation-for="PostNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ByNavn" class="control-label"></label>
                <input asp-for="ByNavn" class="form-control" />
                <span asp-validation-for="ByNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KommuneNavn" class="control-label"></label>
                <input asp-for="KommuneNavn" class="form-control" />
                <span asp-validation-for="KommuneNavn" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Opret" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tilbage til alle lejerkunder</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ElmålingsSystem.MVC/Views/LejerKunde/PutLejerKunde.cshtml
@model MyNamespace.LejerKundeLinked

@{
    ViewData["Title"] = "PutLejerKunde";
}

<h1>Ændre oplysninger</h1>

<h4>LejerKunde</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PutLejerKunde">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="KundeId" />
            <div class="form-group">
                <label asp-for="CprNr" class="control-label"></label>
                <input asp-for="CprNr" class="form-control" />
                <span asp-validation-for="CprNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ForNavn" class="control-label"></label>
                <input asp-for="ForNavn" class="form-control" />
                <span asp-validation-for="ForNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EfterNavn" class="control-label"></label>
                <input asp-for="EfterNavn" class="form-control" />
                <span asp-validation-for="EfterNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VejNavn" class="control-label"></label>
                <input asp-for="VejNavn" class="form-control" />
                <span asp-validation-for="VejNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HusNummer" class="control-label"></label>
                <input asp-for="HusNummer" class="form-control" />
                <span asp-validation-for="HusNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Etage" class="control-label"></label>
                <input asp-for="Etage" class="form-control" />
                <span asp-validation-for="Etage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dør" class="control-label"></label>
                <input asp-for="Dør" class="form-control" />
                <span asp-validation-for="Dør" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostNummer" class="control-label"></label>
                <input asp-for="PostNummer" class="form-control" />
                <span asp-validation-for="PostNummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ByNavn" class="control-label"></label>
                <input asp-for="ByNavn" class="form-control" />
                <span asp-validation-for="ByNavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KommuneNavn" class="control-label"></label>
                <input asp-for="KommuneNavn" class="form-control" />
                <span asp-validation-for="KommuneNavn" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <input type="submit" value="Opdater" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @if (User.IsInRole("Medarbejder"))
    {
        
            <a asp-action="Index">Tilbage til alle lejerkunder</a>
        
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}